# Name of the GitHub Actions workflow.
name: ROS2 CICD

# Controls when the workflow will run.
on:
  # Triggers the workflow on push events but only for the "master" branch.
  push:
    branches: [ "master" ]
  # Triggers the workflow on pull request events targeting the "master" branch.
  pull_request:
    branches: [ "master" ]

jobs:
  # Job 1: Build the image and run tests.
  build-and-test:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # A map of environment variables that are available to all steps.
    env:
      IMAGE_NAME: ros2-project-image

    steps:
      # Step 1.1: Increase Swap Space on the Runner
      # This provides more virtual memory to prevent out-of-memory errors (exit code 137)
      # during memory-intensive compilations like 'colcon build'.
      - name: Increase Runner Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      # Step 1.2: Check out your repository under $GITHUB_WORKSPACE.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 1.3: Build the Docker image from your Dockerfile.
      # We load the image locally to run tests on it.
      - name: Build Docker Image for Testing
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Load the image into the local Docker daemon for testing.
          tags: ${{ env.IMAGE_NAME }}:latest

      # Step 1.4: Run the container and execute build and test commands.
      - name: Run Build and Test inside Container
        run: |
          docker run \
            -d \
            --name ros2_ci_container \
            -v ${{ github.workspace }}/src:/home/rosuser/ros2_ws/src \
            ${{ env.IMAGE_NAME }}:latest
          
          echo "------ Building ROS 2 Workspace ------"
          # Use --executor sequential to force a single-threaded build, which is the most memory-safe option.
          docker exec ros2_ci_container bash -c "colcon build --symlink-install --executor sequential"
          
          echo "------ Running ROS 2 Tests ------"
          # Limit parallel workers here as well for consistency.
          docker exec ros2_ci_container bash -c "colcon test --executor sequential"
          
          echo "------ Displaying Test Results ------"
          # This command will exit with an error code if any tests failed.
          docker exec ros2_ci_container bash -c "colcon test-result --verbose"

  # Job 2: Push the image to Docker Hub.
  push-to-dockerhub:
    # This job will only run if the 'build-and-test' job completes successfully.
    needs: build-and-test
    # This job will only run on a push to the 'master' branch, not on pull requests.
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
      # Step 2.1: Check out your repository.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2.2: Set up Docker Buildx for more advanced build capabilities.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2.3: Log in to Docker Hub using the secrets you created.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2.4: Build the image and push it to your Docker Hub repository.
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # This flag tells the action to push the image.
          # Using the repository name from your file.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ros2_sample_project:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ros2_sample_project:${{ github.sha }}
